Add `run` and `download` install options

diff --git a/static/get b/static/get
--- a/static/get
+++ b/static/get
@@ -5,6 +5,9 @@
 # It's meant to be as simple as possible, so if you're not happy hardcoding a
 # `curl | sh` pipe in your application, you can just download the binary
 # directly with the appropriate URL for your architecture.
+#
+# If you'd like to run it without installing to /usr/local/bin, use `sh -s run`.
+# To download to the current directory, use `sh -s download`.
 
 set +e
 
@@ -21,7 +24,6 @@ case "$(uname -m)" in
 esac
 
 url="https://s3.amazonaws.com/sshx/sshx-${arch}${suffix}.tar.gz"
-temp=$(mktemp)
 
 if [ -z "$NO_COLOR" ]; then
   ansi_reset="\033[0m"
@@ -29,6 +31,26 @@ if [ -z "$NO_COLOR" ]; then
   ansi_error="\033[31m"
   ansi_underline="\033[4m"
 fi
+
+cmd=${1:-install}
+temp=$(mktemp)
+
+case $cmd in
+  "run")
+    path=$(mktemp -d)
+    will_run=1
+    ;;
+  "download")
+    path=$(pwd)
+    ;;
+  "install")
+    path=/usr/local/bin
+    ;;
+  *)
+    printf "${ansi_error}Error: Invalid command. Please use 'run', 'download', or 'install'.\n"
+    exit 1
+    ;;
+esac
 
 printf "${ansi_reset}${ansi_info}↯ Downloading sshx from ${ansi_underline}%s${ansi_reset}\n" "$url"
 http_code=$(curl "$url" -o "$temp" -w "%{http_code}")
@@ -39,11 +61,16 @@ if [ "$http_code" -lt 200 ] || [ "$http_code" -gt 299 ]; then
   exit 1
 fi
 
-printf "\n${ansi_reset}${ansi_info}↯ Adding sshx binary to ${ansi_underline}%s${ansi_reset}\n" "/usr/local/bin"
-if [ "$(id -u)" -ne 0 ]; then
-  sudo tar xf "$temp" -C /usr/local/bin
+printf "\n${ansi_reset}${ansi_info}↯ Adding sshx binary to ${ansi_underline}%s${ansi_reset}\n" "$path"
+if [ "$(id -u)" -ne 0 ] && [ "$path" = "/usr/local/bin" ]; then
+  sudo tar xf "$temp" -C "$path" || exit 1
 else
-  tar xf "$temp" -C /usr/local/bin
+  tar xf "$temp" -C "$path" || exit 1
 fi
 
 printf "\n${ansi_reset}${ansi_info}↯ Done! You can now run sshx.${ansi_reset}\n"
+
+if [ -n "$will_run" ]; then
+  "$path/sshx"
+  rm -f "$path/sshx"
+fi
